server:
  port: 8765

spring:
  application:
    name: hr-api-gateway
  cloud:
    gateway:
      routes:
        - id: hr-worker
          uri: lb://hr-worker/workers
          predicates:
            - Path=/workers/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




